# Generated by Django 5.2.18 on 2026-10-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_payment_checkout_and_refund_due'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('mark_payment_refunded', 'Can mark payments as refunded')]},
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refund_due', 'Refund Due'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
